security:
    encoders:
        App\Entity\Usuario: { algorithm: bcrypt , cost: 13 }

    role_hierarchy:
        ROLE_PROFESOR:  ROLE_ESTUDIANTE
        ROLE_JEFETECNICO:  ROLE_TECNICO
        ROLE_JEFETECNICOINSTITUCIONAL:  ROLE_JEFETECNICO

    providers:
        usuarios:
            entity: { class: App:Usuario}


    firewalls:
        api_area:
            pattern:    ^/api/*
            anonymous: ~
            provider: usuarios
            guard:
                authenticators:
                    - App\Security\ApiTokenAuthenticator
        secured_area:
            pattern:    ^/*
            user_checker: App\Security\UserChecker
            form_login:
                login_path: index
                check_path: check
                default_target_path: index
                always_use_default_target_path: true
             #   csrf_token_generator: security.csrf.token_manager
            logout:
                path:   logout
                target: index
                handlers: [app.logoutlistener]
            anonymous: ~
            remember_me:
                secret:  '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path: index
            guard:
                authenticators:
                    - App\Security\LdapAuthenticator

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/translate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/static, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/staticar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/estatica, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #INICIO de INFORMACION QUE GESTIONA SOLAMENTE EL ADMIN
        - { path: ^/facultad, roles: ROLE_ADMIN }
        - { path: ^/faculty, roles: ROLE_ADMIN }
        - { path: ^/moyen, roles: ROLE_ADMIN }
        - { path: ^/usuario$, roles: ROLE_ADMIN }
        - { path: ^/user$, roles: ROLE_ADMIN }
        - { path: ^/utilisateur$, roles: ROLE_ADMIN }
        - { path: ^/usuario/new, roles: ROLE_ADMIN }
        - { path: ^/user/new, roles: ROLE_ADMIN }
        - { path: ^/utilisateur/new, roles: ROLE_ADMIN }
        - { path: ^/usuario\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/user\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/utilisateur\d+/delete, roles: ROLE_ADMIN }
        #FIN de INFORMACION QUE GESTIONA SOLAMENTE EL ADMIN
        #INICIO de INFORMACION QUE GESTIONA SOLAMENTE EL JEFE DE LOS TECNICOS
        - { path: ^/laboratorio/new, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratory/new, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratoire/new, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratorio/\d+/edit, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratory/\d+/edit, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratoire/\d+/edit, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratorio/\d+/delete, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratory/\d+/delete, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/laboratoire/\d+/delete, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/propiedad/\d+/searchbypieza, roles: ROLE_TECNICO }
        - { path: ^/property/\d+/searchbypieza, roles: ROLE_TECNICO }
        - { path: ^/propriete/\d+/searchbypieza, roles: ROLE_TECNICO }
        - { path: ^/propiedad/\d+/searchbyperiferico, roles: ROLE_TECNICO }
        - { path: ^/property/\d+/searchbyperiferico, roles: ROLE_TECNICO }
        - { path: ^/propriete/\d+/searchbyperiferico, roles: ROLE_TECNICO }
        - { path: ^/propiedad, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/property, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/propriete, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/periferico, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/peripheral, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/peripherique, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/pieza/\d+/searchbypieza, roles: ROLE_TECNICO }
        - { path: ^/piece/\d+/searchbypieza, roles: ROLE_TECNICO }
        - { path: ^/pièce/\d+/searchbypieza, roles: ROLE_TECNICO }
        - { path: ^/pieza, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/piece, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/pièce, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/tiporeparacion, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/typereparation, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        - { path: ^/typeréparation, roles: ROLE_JEFETECNICOINSTITUCIONAL }
        #FIN INFORMACION QUE GESTIONA SOLAMENTE EL JEFE DE LOS TECNICOS

        - { path: ^/pc/\d+/new, roles: ROLE_JEFETECNICO }
        - { path: ^/computadora/\d+/new, roles: ROLE_JEFETECNICO }
        - { path: ^/ordinateur/\d+/new, roles: ROLE_JEFETECNICO }
        - { path: ^/pc/\d+/delete, roles: [ROLE_JEFETECNICO] }
        - { path: ^/computadora/\d+/delete, roles: [ROLE_JEFETECNICO] }
        - { path: ^/ordinateur/\d+/delete, roles: [ROLE_JEFETECNICO] }
        - { path: ^/reparacion/\d+/new, roles: ROLE_JEFETECNICO }
        - { path: ^/reparation/\d+/new, roles: ROLE_JEFETECNICO }
        - { path: ^/reparer/\d+/new, roles: ROLE_JEFETECNICO }
        - { path: ^/reparacion/\d+/edit, roles: ROLE_JEFETECNICO }
        - { path: ^/reparation/\d+/edit, roles: ROLE_JEFETECNICO }
        - { path: ^/reparer/\d+/edit, roles: ROLE_JEFETECNICO }
        - { path: ^/reparacion/\d+/delete, roles: ROLE_JEFETECNICO }
        - { path: ^/reparation/\d+/delete, roles: ROLE_JEFETECNICO }
        - { path: ^/reparer/\d+/delete, roles: ROLE_JEFETECNICO }

        #INICIO de INFORMACION QUE GESTIONAN LOS TECNICOS DE LABORATORIO
        - { path: ^/laboratorio, roles: ROLE_TECNICO }
        - { path: ^/laboratory, roles: ROLE_TECNICO }
        - { path: ^/laboratoire, roles: ROLE_TECNICO }
        - { path: ^/pc, roles: ROLE_TECNICO }
        - { path: ^/computadora, roles: ROLE_TECNICO }
        - { path: ^/ordinateur, roles: ROLE_TECNICO }
        - { path: ^/registropropiedad, roles: ROLE_TECNICO }
        - { path: ^/propertyregister, roles: ROLE_TECNICO }
        - { path: ^/proprietedenregistrement, roles: ROLE_TECNICO }
        - { path: ^/registropieza, roles: ROLE_TECNICO }
        - { path: ^/pieceregister, roles: ROLE_TECNICO }
        - { path: ^/piecededisque, roles: ROLE_TECNICO }
        - { path: ^/registroperiferico, roles: ROLE_TECNICO }
        - { path: ^/peripheralregister, roles: ROLE_TECNICO }
        - { path: ^/enregistrementperipherique, roles: ROLE_TECNICO }
        - { path: ^/reparacion, roles: ROLE_TECNICO }
        - { path: ^/reparation, roles: ROLE_TECNICO }
        - { path: ^/reparer, roles: ROLE_TECNICO }
        #FIN de INFORMACION QUE GESTIONAN LOS TECNICOS DE LABORATORIO

        #INFORMACION QUE GESTIONAN LOS ESTUDIANTES Y PROFESORES
        - { path: ^/reservacion/laboratorio, roles: [ROLE_PROFESOR, ROLE_TECNICO] }
        - { path: ^/reservation/laboratory, roles:  [ROLE_PROFESOR, ROLE_TECNICO] }
        - { path: ^/reservation/laboratoire, roles: [ROLE_PROFESOR, ROLE_TECNICO] }
        - { path: ^/reservation/pc/, roles: [ROLE_ESTUDIANTE, ROLE_TECNICO] }
        - { path: ^/reservacion/computadora/, roles: [ROLE_ESTUDIANTE, ROLE_TECNICO] }
        - { path: ^/reservation/calculateur/, roles: [ROLE_ESTUDIANTE, ROLE_TECNICO] }
        - { path: ^/machinetime, roles: ROLE_TECNICO }
        - { path: ^/tiempomaquina, roles: ROLE_TECNICO }
        - { path: ^/tempsmachine, roles: ROLE_TECNICO }
        - { path: ^/api/requesttoken, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: IS_AUTHENTICATED_FULLY }